---
name: "Linting"

on:
  push:

# Disable all default permissions
permissions: {}

jobs:
  go-mod-tidy:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod

      - name: go mod tidy
        run: go mod tidy -diff

  golangci-lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: v1.61.0
          args: --config=.github/linters/.golangci.yml

  super-linter:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@b92721f792f381cedc002ecdbb9847a15ece5bb8 # v7.1.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Prefer our golangci-lint
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false

  mega-linter:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: MegaLinter
        uses: oxsecurity/megalinter@c217fe8f7bc9207062a084e989bd97efd56e7b9a # v8.0.0
        env:
          VALIDATE_ALL_CODEBASE: true
          # SPELL is a little bit tricky
          # GO is linted with our golangci-lint configuration
          DISABLE: SPELL,GO
          # markdown-table-formatter mess with prettier
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_TABLE_FORMATTER
          REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yaml
          # Stop linting mega-linter generated files
          LOG_FILE: ${{ runner.temp }}/mega-linter.log
          REPORT_OUTPUT_FOLDER: ${{ runner.temp }}/megalinter-reports
