---
name: "Linting"

on:
  push:

# Disable all default permissions
permissions: {}

jobs:
  go-mod-tidy:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod

      - name: go mod tidy
        run: go mod tidy -diff

  golangci-lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: v1.61.0
          args: --config=.github/linters/.golangci.yml

  super-linter:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter/slim@b92721f792f381cedc002ecdbb9847a15ece5bb8 # v7.1.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Prefer our golangci-lint
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false

  mega-linter:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: MegaLinter
        uses: oxsecurity/megalinter@1fc052d03c7a43c78fe0fee19c9d648b749e0c01 # v8.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          # SPELL is a little bit tricky
          # GO is linted with our golangci-lint configuration
          DISABLE: SPELL,GO
          # markdown-table-formatter mess with prettier
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_TABLE_FORMATTER
          REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yaml
          # Stop linting mega-linter generated files
          LOG_FILE: ${{ runner.temp }}/mega-linter.log
          REPORT_OUTPUT_FOLDER: ${{ runner.temp }}/megalinter-reports
